spring.application.name=error-auditor-service

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# AWS Configuration
spring.cloud.aws.region.static=us-east-1

server.port=4200
# SQS Configuration
queue.name=T04N_GABRIEL_EDUARDO_PHILIPPSEN_WANDSCHEER.fifo
